logging:
  level:
    root: INFO
    com.github.jeffrade.github: DEBUG
    org.springframework: DEBUG
    okhttp3: DEBUG
    retrofit2: DEBUG

square:
  domain: https://connect.squareup.com
  app:
    name: ${SQUAREUP_APP_NAME}
  api:
    applicationId: ${SQUAREUP_API_APP_ID}
    acceptToken: ${SQUAREUP_API_ACC_TOKEN}
    applicationSecret: ${SQUAREUP_API_APP_SECRET}